### ISSUE TITLE
Sending both plain and html parts using PMTA

### ISSUE THREAD

**Issue by Mayur700** [kyokenn/python-port25#3]
Hi

I used to send the both html and plain parts of the email using the python  SMTP , but I can' t figure out how to do the same using the PMTA send.py script. Can you please help me with this. I've tried using multipart and boundary in the content type but  when i receive the mail I get the html as html and code and then text content .

**Comment by kyokenn** [comment]
Can you provide an examples of code?
You have to do something like this: https://docs.python.org/2/library/email-examples.html
And then:
port25_msg.addMergeData(email_msg.as_string())

**Comment by Mayur700** [comment]
Hi Okami, here is the code	
# ***********************************************************************
	# The Headers part.
	dateHeader = 'Date: ' +formatdate(localtime=True)
	x_Sender         = 'info@sendercox.com'			
	if hostingType =='shared':
		x_Sender = xSenderId
	xSender         = 'X-Sender:' + x_Sender
	Sender         = 'Sender:' + x_Sender
	xReceiver       = 'X-Receiver:' + toAddress
	xVMTA           = 'X-virtual-mta:' + vmtaName
	mimeVersion     = 'MIME-Version: 1.0'
	preced          = 'Precedence: bulk'
	replytoHeader   = 'Reply-To:' + '<'+replyTo+'>'
	ctype           = 'Content-Type: text/html; charset=utf-8'
	ctEncode 		= 'Content-Transfer-Encoding: 7bit'
	# ***********************************************************************
	
	emailHeaders = dateHeader+'\12'+xSender+'\12'+xReceiver+'\12'+xVMTA+'\12'+xEnvId+'\12'+xContactID+'\12'+xclientID+'\12'+xcampaignID+'\12'+xfeedbackID+'\12'+xReportAbuseTo+'\12'+fromHeader+'\12'+toheader+'\12'+subjectHeader+'\12'+listUns+'\12'+errorsTO+'\12'+mimeVersion+'\12'+preced+'\12'+replytoHeader+'\12'+ctype+'\12'+ctEncode+'\12'+htmlBody
	#~ The PMTA connection
	conn = Connection(uri=str(mtaIP),port=25)
	#senderEmail1='info@sendercox.com'
	msg = Message(x_Sender)
	ts = int(time.time())
	rcpt = None
	#~ print senderEmail1
	try:
		rcpt = Recipient(toAddress)
		msg.addRecipient(rcpt)
		#msg.addDateHeader()
		msg.setVirtualMta(vmtaName)
		#msg.setEnvelopeId(mLID)
		#msg.setJobId(ts)
		msg.addMergeData(emailHeaders)
		msg.setEncoding(0)
		msg.setReturnType(0)
		conn.submit(msg)
		print "Mail sent"
	except PmtaError, e:
			print "PMTA Error: ",e
	except Exception, e:
			print "Some other error",e.args

**Comment by kyokenn** [comment]
Do not create e-mail message's source by yourself. There is a library "email.mime", which is included with python. You have to use multipart-alternative message type for a messages with mixed content (html+text), check out last example in https://docs.python.org/2/library/email-examples.html

**Comment by Mayur700** [comment]
Thank You Okami, That's a great a help to me since I was unable to do so earlier........ :) as i'm unfamiliar with it.

**Comment by Mayur700** [comment]
Hi Okami,
When I try to install the package on windows 8.1 pc it throws the following error..

***********************************************************************
F:\MayurEMMbackup\python-port25-0.0.3>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from port25 import __author__, __license__, __version__
  File "src\port25\__init__.py", line 23, in <module>
    pmta = CDLL("libpmta.so")
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

F:\MayurEMMbackup\python-port25-0.0.3>
***********************************************************************

**Comment by kyokenn** [comment]
Do you have installed "libpmta.so" from PowerMTA?

**Comment by Mayur700** [comment]
How can I install the libpmta.so file ??
Because I've PMTA installed on the other system.(centos)

**Comment by Mayur700** [comment]
HI Okami, I'm still facing the same error.How can I get the libpmta.so installed on my windows 8 pc

**Comment by kyokenn** [comment]
This library comes with PowerMTA installation. You have to install PowerMTA first.

**Comment by Mayur700** [comment]
In that case I've a colleague of mine who has installed the PowerMTA on a public server(generally a  centos system) and he has installed the python package relating to Powermta in his Local computer(without the powerMTA being installed).
